name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-dev libgl1 pkg-config
          pip install numpy pandas scikit-learn opencv-python matplotlib nbconvert

      - name: Convert Notebook to Script
        run: jupyter nbconvert --to script Ananya_Lab5.ipynb

      - name: Run test script with virtual display
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python Ananya_Lab5.py
